---
cog_bundle_version: 5
name: grafana
description: Grafana Graphs in Chat
version: 0.2.2
docker:
  image: "kickstarter/grafana"
  tag: "latest"
config:
  env:
  - var: GRAFANA_URL
    description: "URL to your Grafana instance"
  - var: GRAFANA_API_KEY
    description: "API key for your Grafana instnace"
commands:
  dashboards:
    executable: "/home/bundle/cog-command"
    description: List dashboards
    rules:
      - allow
  panels:
    executable: "/home/bundle/cog-command"
    description: List panels in a dashboard
    rules:
      - allow
  graph:
    executable: "/home/bundle/cog-command"
    description: View a graph
    rules:
      - allow
